[2025-03-02T00:11:32.952+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_messages.messages_load manual__2025-03-02T00:11:14.373439+00:00 [queued]>
[2025-03-02T00:11:32.983+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_messages.messages_load manual__2025-03-02T00:11:14.373439+00:00 [queued]>
[2025-03-02T00:11:32.984+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-02T00:11:33.034+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): messages_load> on 2025-03-02 00:11:14.373439+00:00
[2025-03-02T00:11:33.053+0000] {standard_task_runner.py:57} INFO - Started process 1343 to run task
[2025-03-02T00:11:33.075+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'new_messages', 'messages_load', 'manual__2025-03-02T00:11:14.373439+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/mess_cluster.py', '--cfg-path', '/tmp/tmpg6x59k23']
[2025-03-02T00:11:33.084+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask messages_load
[2025-03-02T00:11:33.486+0000] {task_command.py:416} INFO - Running <TaskInstance: new_messages.messages_load manual__2025-03-02T00:11:14.373439+00:00 [running]> on host 187a59cb65df
[2025-03-02T00:11:33.810+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_messages' AIRFLOW_CTX_TASK_ID='messages_load' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:11:14.373439+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T00:11:14.373439+00:00'
[2025-03-02T00:11:34.904+0000] {docker.py:367} INFO - Starting docker container from image messages-loader:latest
[2025-03-02T00:12:50.094+0000] {docker.py:438} INFO - WARNING:selenium.webdriver.common.selenium_manager:Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event)
[2025-03-02T00:15:21.865+0000] {docker.py:438} INFO - ERROR:root:Timeout error: HTTPConnectionPool(host='localhost', port=58105): Read timed out. (read timeout=120)
[2025-03-02T00:17:21.774+0000] {docker.py:438} INFO - INFO:root:News fetched UNsuccessfully.
[2025-03-02T00:19:00.276+0000] {docker.py:438} INFO - INFO:root:News fetched UNsuccessfully.
[2025-03-02T00:19:21.089+0000] {docker.py:438} INFO - INFO:root:News page fetched successfully.
[2025-03-02T00:20:07.235+0000] {docker.py:438} INFO - INFO:root:News fetched UNsuccessfully.
[2025-03-02T00:20:44.057+0000] {docker.py:438} INFO - INFO:root:News page fetched successfully.
[2025-03-02T00:21:13.530+0000] {docker.py:438} INFO - INFO:root:News page fetched successfully.
[2025-03-02T00:21:17.008+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:17.231+0000] {docker.py:438} INFO - [nltk_data]   Unzipping corpora/stopwords.zip.
[2025-03-02T00:21:17.620+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:17.654+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:21.928+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:21.937+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:24.483+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:24.486+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:25.216+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:25.224+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:26.177+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:26.227+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:28.873+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:28.912+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:31.837+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:31.840+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:32.616+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:32.620+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:33.665+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:33.666+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:34.771+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:34.773+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:35.390+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:35.418+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:35.491+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:35.492+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:39.164+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:39.167+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:40.892+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:40.895+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:41.518+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:41.594+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:43.194+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:43.196+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:43.852+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:43.864+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:45.175+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:45.178+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:46.830+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:46.834+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:49.282+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:49.412+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:49.586+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:49.588+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:51.721+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:51.728+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:56.876+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:56.896+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:21:58.194+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:21:58.232+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:22:01.057+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:22:01.058+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:22:01.822+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:22:01.827+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:22:02.520+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:22:02.542+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:22:10.409+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:22:10.418+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:22:11.751+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:22:11.754+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:22:12.205+0000] {docker.py:438} INFO - Traceback (most recent call last):
[2025-03-02T00:22:12.217+0000] {docker.py:438} INFO - File "/workdir/Parsing.py", line 168, in <module>
[2025-03-02T00:22:12.257+0000] {docker.py:438} INFO - load_data()
[2025-03-02T00:22:12.342+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
[2025-03-02T00:22:12.364+0000] {docker.py:438} INFO - return self.main(*args, **kwargs)
[2025-03-02T00:22:12.403+0000] {docker.py:438} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:22:12.425+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1082, in main
[2025-03-02T00:22:12.429+0000] {docker.py:438} INFO -     rv = self.invoke(ctx)
[2025-03-02T00:22:12.473+0000] {docker.py:438} INFO -          ^^^^^^^^^^^^^^^^
[2025-03-02T00:22:12.577+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
[2025-03-02T00:22:12.616+0000] {docker.py:438} INFO - return ctx.invoke(self.callback, **ctx.params)
[2025-03-02T00:22:12.628+0000] {docker.py:438} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:22:12.629+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 788, in invoke
[2025-03-02T00:22:12.662+0000] {docker.py:438} INFO - return __callback(*args, **kwargs)
[2025-03-02T00:22:12.672+0000] {docker.py:438} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:22:12.699+0000] {docker.py:438} INFO - File "/workdir/Parsing.py", line 163, in load_data
[2025-03-02T00:22:12.723+0000] {docker.py:438} INFO - df.to_csv(data_path, index=False)
[2025-03-02T00:22:12.728+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
[2025-03-02T00:22:12.731+0000] {docker.py:438} INFO - return func(*args, **kwargs)
[2025-03-02T00:22:12.732+0000] {docker.py:438} INFO - ^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:22:12.749+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
[2025-03-02T00:22:12.769+0000] {docker.py:438} INFO - return DataFrameRenderer(formatter).to_csv(
[2025-03-02T00:22:12.772+0000] {docker.py:438} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:22:12.790+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
[2025-03-02T00:22:12.801+0000] {docker.py:438} INFO -     csv_formatter.save()
[2025-03-02T00:22:12.804+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
[2025-03-02T00:22:12.806+0000] {docker.py:438} INFO - with get_handle(
[2025-03-02T00:22:12.811+0000] {docker.py:438} INFO -          ^^^^^^^^^^^
[2025-03-02T00:22:12.813+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/pandas/io/common.py", line 749, in get_handle
[2025-03-02T00:22:12.858+0000] {docker.py:438} INFO - check_parent_directory(str(handle))
[2025-03-02T00:22:12.882+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/pandas/io/common.py", line 616, in check_parent_directory
[2025-03-02T00:22:12.924+0000] {docker.py:438} INFO - raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2025-03-02T00:22:12.949+0000] {docker.py:438} INFO - OSError: Cannot save file into a non-existent directory: '/opt/***/data/raw'
[2025-03-02T00:22:29.756+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-03-02T00:22:31.613+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=new_messages, task_id=messages_load, execution_date=20250302T001114, start_date=20250302T001132, end_date=20250302T002231
[2025-03-02T00:22:32.396+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task messages_load (Docker container failed: {'StatusCode': 1}; 1343)
[2025-03-02T00:22:32.522+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-02T00:22:33.140+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
